// AUTO-GENERATED by Dream Studio. Do not edit.
// 编译前扫描源码生成：引用所有 DreamComponent 子类，供 ComponentFactory 反射注册。
package dream.engine.ecs
{
	import dream.engine.animation.AnimStateMachine;
	import dream.engine.animation.AnimationPlayer;
	import dream.engine.audio.AudioListener;
	import dream.engine.audio.AudioSource;
	import dream.engine.physics2d.BoxCollider2D;
	import dream.engine.physics2d.CircleCollider2D;
	import dream.engine.physics2d.Collider2D;
	import dream.engine.physics2d.RigidBody2D;
	import dream.engine.render.CameraComponent;
	import dream.engine.render.DisplayComponent;
	import dream.engine.render.SpriteRenderer;
	import dream.engine.transform.Transform;
	import dream.engine.ui.Button;
	import dream.engine.ui.Canvas;
	import dream.engine.ui.CanvasScaler;
	import dream.engine.ui.Image;
	import dream.engine.ui.Layout;
	import dream.engine.ui.Mask;
	import dream.engine.ui.RectTransform;
	import dream.engine.ui.ScrollView;
	import dream.engine.ui.Scrollbar;
	import dream.engine.ui.Text;
	import dream.engine.ui.UIDrawable;

	/**
	 * 自动生成的组件索引：引用所有 DreamComponent 子类（触发类链接）。
	 * ComponentFactory.ensureInitialized 遍历 ALL，用 describeType 反射
	 * 构造函数签名，自动注册无参构造且非 EXCLUDED 的子类。
	 */
	public final class ComponentIndex
	{
		public static const ALL:Array = [
			AnimStateMachine,  // dream.engine.animation.AnimStateMachine
			AnimationPlayer,  // dream.engine.animation.AnimationPlayer
			AudioListener,  // dream.engine.audio.AudioListener
			AudioSource,  // dream.engine.audio.AudioSource
			BoxCollider2D,  // dream.engine.physics2d.BoxCollider2D
			CircleCollider2D,  // dream.engine.physics2d.CircleCollider2D
			Collider2D,  // dream.engine.physics2d.Collider2D
			RigidBody2D,  // dream.engine.physics2d.RigidBody2D
			CameraComponent,  // dream.engine.render.CameraComponent
			DisplayComponent,  // dream.engine.render.DisplayComponent
			SpriteRenderer,  // dream.engine.render.SpriteRenderer
			Transform,  // dream.engine.transform.Transform
			Button,  // dream.engine.ui.Button
			Canvas,  // dream.engine.ui.Canvas
			CanvasScaler,  // dream.engine.ui.CanvasScaler
			Image,  // dream.engine.ui.Image
			Layout,  // dream.engine.ui.Layout
			Mask,  // dream.engine.ui.Mask
			RectTransform,  // dream.engine.ui.RectTransform
			ScrollView,  // dream.engine.ui.ScrollView
			Scrollbar,  // dream.engine.ui.Scrollbar
			Text,  // dream.engine.ui.Text
			UIDrawable  // dream.engine.ui.UIDrawable
		];
	}
}
